apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol:get-list-watch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-list-watch
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    namespace: prometheus
